import {
  airtableCreateRecordsTool,
  airtableGetRecordTool,
  airtableListRecordsTool,
  airtableUpdateRecordTool,
} from '@/tools/airtable'
import { arxivGetAuthorPapersTool, arxivGetPaperTool, arxivSearchTool } from '@/tools/arxiv'
import {
  asanaAddCommentTool,
  asanaCreateTaskTool,
  asanaGetProjectsTool,
  asanaGetTaskTool,
  asanaSearchTasksTool,
  asanaUpdateTaskTool,
} from '@/tools/asana'
import { browserUseRunTaskTool } from '@/tools/browser_use'
import { clayPopulateTool } from '@/tools/clay'
import {
  confluenceCreateCommentTool,
  confluenceCreatePageTool,
  confluenceDeleteAttachmentTool,
  confluenceDeleteCommentTool,
  confluenceDeletePageTool,
  confluenceGetSpaceTool,
  confluenceListAttachmentsTool,
  confluenceListCommentsTool,
  confluenceListLabelsTool,
  confluenceListSpacesTool,
  confluenceRetrieveTool,
  confluenceSearchTool,
  confluenceUpdateCommentTool,
  confluenceUpdateTool,
} from '@/tools/confluence'
import {
  discordAddReactionTool,
  discordArchiveThreadTool,
  discordAssignRoleTool,
  discordBanMemberTool,
  discordCreateChannelTool,
  discordCreateInviteTool,
  discordCreateRoleTool,
  discordCreateThreadTool,
  discordCreateWebhookTool,
  discordDeleteChannelTool,
  discordDeleteInviteTool,
  discordDeleteMessageTool,
  discordDeleteRoleTool,
  discordDeleteWebhookTool,
  discordEditMessageTool,
  discordExecuteWebhookTool,
  discordGetChannelTool,
  discordGetInviteTool,
  discordGetMemberTool,
  discordGetMessagesTool,
  discordGetServerTool,
  discordGetUserTool,
  discordGetWebhookTool,
  discordJoinThreadTool,
  discordKickMemberTool,
  discordLeaveThreadTool,
  discordPinMessageTool,
  discordRemoveReactionTool,
  discordRemoveRoleTool,
  discordSendMessageTool,
  discordUnbanMemberTool,
  discordUnpinMessageTool,
  discordUpdateChannelTool,
  discordUpdateMemberTool,
  discordUpdateRoleTool,
} from '@/tools/discord'
import { elevenLabsTtsTool } from '@/tools/elevenlabs'
import {
  exaAnswerTool,
  exaFindSimilarLinksTool,
  exaGetContentsTool,
  exaResearchTool,
  exaSearchTool,
} from '@/tools/exa'
import { fileParseTool } from '@/tools/file'
import { crawlTool, extractTool, mapTool, scrapeTool, searchTool } from '@/tools/firecrawl'
import { functionExecuteTool } from '@/tools/function'
import {
  githubAddAssigneesTool,
  githubAddLabelsTool,
  githubCancelWorkflowRunTool,
  githubCloseIssueTool,
  githubClosePRTool,
  githubCommentTool,
  githubCreateBranchTool,
  githubCreateFileTool,
  githubCreateIssueTool,
  githubCreatePRTool,
  githubCreateProjectTool,
  githubCreateReleaseTool,
  githubDeleteBranchTool,
  githubDeleteCommentTool,
  githubDeleteFileTool,
  githubDeleteProjectTool,
  githubDeleteReleaseTool,
  githubGetBranchProtectionTool,
  githubGetBranchTool,
  githubGetFileContentTool,
  githubGetIssueTool,
  githubGetPRFilesTool,
  githubGetProjectTool,
  githubGetReleaseTool,
  githubGetTreeTool,
  githubGetWorkflowRunTool,
  githubGetWorkflowTool,
  githubIssueCommentTool,
  githubLatestCommitTool,
  githubListBranchesTool,
  githubListIssueCommentsTool,
  githubListIssuesTool,
  githubListPRCommentsTool,
  githubListPRsTool,
  githubListProjectsTool,
  githubListReleasesTool,
  githubListWorkflowRunsTool,
  githubListWorkflowsTool,
  githubMergePRTool,
  githubPrTool,
  githubRemoveLabelTool,
  githubRepoInfoTool,
  githubRequestReviewersTool,
  githubRerunWorkflowTool,
  githubTriggerWorkflowTool,
  githubUpdateBranchProtectionTool,
  githubUpdateCommentTool,
  githubUpdateFileTool,
  githubUpdateIssueTool,
  githubUpdatePRTool,
  githubUpdateProjectTool,
  githubUpdateReleaseTool,
} from '@/tools/github'
import {
  gmailAddLabelTool,
  gmailArchiveTool,
  gmailDeleteTool,
  gmailDraftTool,
  gmailMarkReadTool,
  gmailMarkUnreadTool,
  gmailMoveTool,
  gmailReadTool,
  gmailRemoveLabelTool,
  gmailSearchTool,
  gmailSendTool,
  gmailUnarchiveTool,
} from '@/tools/gmail'
import { searchTool as googleSearchTool } from '@/tools/google'
import {
  googleCalendarCreateTool,
  googleCalendarGetTool,
  googleCalendarInviteTool,
  googleCalendarListTool,
  googleCalendarQuickAddTool,
} from '@/tools/google_calendar'
import { googleDocsCreateTool, googleDocsReadTool, googleDocsWriteTool } from '@/tools/google_docs'
import {
  googleDriveCreateFolderTool,
  googleDriveDownloadTool,
  googleDriveGetContentTool,
  googleDriveListTool,
  googleDriveUploadTool,
} from '@/tools/google_drive'
import { googleFormsGetResponsesTool } from '@/tools/google_form'
import {
  googleSheetsAppendTool,
  googleSheetsReadTool,
  googleSheetsUpdateTool,
  googleSheetsWriteTool,
} from '@/tools/google_sheets'
import {
  createMattersExportTool,
  createMattersHoldsTool,
  createMattersTool,
  downloadExportFileTool,
  listMattersExportTool,
  listMattersHoldsTool,
  listMattersTool,
} from '@/tools/google_vault'
import { guardrailsValidateTool } from '@/tools/guardrails'
import { requestTool as httpRequest } from '@/tools/http'
import {
  hubspotCreateCompanyTool,
  hubspotCreateContactTool,
  hubspotGetCompanyTool,
  hubspotGetContactTool,
  hubspotGetUsersTool,
  hubspotListCompaniesTool,
  hubspotListContactsTool,
  hubspotListDealsTool,
  hubspotSearchCompaniesTool,
  hubspotSearchContactsTool,
  hubspotUpdateCompanyTool,
  hubspotUpdateContactTool,
} from '@/tools/hubspot'
import { huggingfaceChatTool } from '@/tools/huggingface'
import {
  hunterCompaniesFindTool,
  hunterDiscoverTool,
  hunterDomainSearchTool,
  hunterEmailCountTool,
  hunterEmailFinderTool,
  hunterEmailVerifierTool,
} from '@/tools/hunter'
import { searchTool as jinaSearchTool, readUrlTool } from '@/tools/jina'
import {
  jiraAddCommentTool,
  jiraAddWatcherTool,
  jiraAddWorklogTool,
  jiraAssignIssueTool,
  jiraBulkRetrieveTool,
  jiraCreateIssueLinkTool,
  jiraDeleteAttachmentTool,
  jiraDeleteCommentTool,
  jiraDeleteIssueLinkTool,
  jiraDeleteIssueTool,
  jiraDeleteWorklogTool,
  jiraGetAttachmentsTool,
  jiraGetCommentsTool,
  jiraGetWorklogsTool,
  jiraRemoveWatcherTool,
  jiraRetrieveTool,
  jiraSearchIssuesTool,
  jiraTransitionIssueTool,
  jiraUpdateCommentTool,
  jiraUpdateTool,
  jiraUpdateWorklogTool,
  jiraWriteTool,
} from '@/tools/jira'
import {
  knowledgeCreateDocumentTool,
  knowledgeSearchTool,
  knowledgeUploadChunkTool,
} from '@/tools/knowledge'
import {
  linearAddLabelToIssueTool,
  linearAddLabelToProjectTool,
  linearArchiveIssueTool,
  linearArchiveLabelTool,
  linearArchiveProjectTool,
  linearCreateAttachmentTool,
  linearCreateCommentTool,
  linearCreateCustomerRequestTool,
  linearCreateCustomerStatusTool,
  linearCreateCustomerTierTool,
  linearCreateCustomerTool,
  linearCreateCycleTool,
  linearCreateFavoriteTool,
  linearCreateIssueRelationTool,
  linearCreateIssueTool,
  linearCreateLabelTool,
  linearCreateProjectLabelTool,
  linearCreateProjectLinkTool,
  linearCreateProjectMilestoneTool,
  linearCreateProjectStatusTool,
  linearCreateProjectTool,
  linearCreateProjectUpdateTool,
  linearCreateWorkflowStateTool,
  linearDeleteAttachmentTool,
  linearDeleteCommentTool,
  linearDeleteCustomerStatusTool,
  linearDeleteCustomerTierTool,
  linearDeleteCustomerTool,
  linearDeleteIssueRelationTool,
  linearDeleteIssueTool,
  linearDeleteProjectLabelTool,
  linearDeleteProjectMilestoneTool,
  linearDeleteProjectStatusTool,
  linearDeleteProjectTool,
  linearGetActiveCycleTool,
  linearGetCustomerTool,
  linearGetCycleTool,
  linearGetIssueTool,
  linearGetProjectTool,
  linearGetViewerTool,
  linearListAttachmentsTool,
  linearListCommentsTool,
  linearListCustomerRequestsTool,
  linearListCustomerStatusesTool,
  linearListCustomersTool,
  linearListCustomerTiersTool,
  linearListCyclesTool,
  linearListFavoritesTool,
  linearListIssueRelationsTool,
  linearListLabelsTool,
  linearListNotificationsTool,
  linearListProjectLabelsTool,
  linearListProjectMilestonesTool,
  linearListProjectStatusesTool,
  linearListProjectsTool,
  linearListProjectUpdatesTool,
  linearListTeamsTool,
  linearListUsersTool,
  linearListWorkflowStatesTool,
  linearMergeCustomersTool,
  linearReadIssuesTool,
  linearRemoveLabelFromIssueTool,
  linearRemoveLabelFromProjectTool,
  linearSearchIssuesTool,
  linearUnarchiveIssueTool,
  linearUpdateAttachmentTool,
  linearUpdateCommentTool,
  linearUpdateCustomerRequestTool,
  linearUpdateCustomerStatusTool,
  linearUpdateCustomerTierTool,
  linearUpdateCustomerTool,
  linearUpdateIssueTool,
  linearUpdateLabelTool,
  linearUpdateNotificationTool,
  linearUpdateProjectLabelTool,
  linearUpdateProjectMilestoneTool,
  linearUpdateProjectStatusTool,
  linearUpdateProjectTool,
  linearUpdateWorkflowStateTool,
} from '@/tools/linear'
import { linkupSearchTool } from '@/tools/linkup'
import { mem0AddMemoriesTool, mem0GetMemoriesTool, mem0SearchMemoriesTool } from '@/tools/mem0'
import { memoryAddTool, memoryDeleteTool, memoryGetAllTool, memoryGetTool } from '@/tools/memory'
import {
  microsoftExcelReadTool,
  microsoftExcelTableAddTool,
  microsoftExcelWriteTool,
} from '@/tools/microsoft_excel'
import {
  microsoftPlannerCreateBucketTool,
  microsoftPlannerCreateTaskTool,
  microsoftPlannerDeleteBucketTool,
  microsoftPlannerDeleteTaskTool,
  microsoftPlannerGetTaskDetailsTool,
  microsoftPlannerListBucketsTool,
  microsoftPlannerListPlansTool,
  microsoftPlannerReadBucketTool,
  microsoftPlannerReadPlanTool,
  microsoftPlannerReadTaskTool,
  microsoftPlannerUpdateBucketTool,
  microsoftPlannerUpdateTaskDetailsTool,
  microsoftPlannerUpdateTaskTool,
} from '@/tools/microsoft_planner'
import {
  microsoftTeamsDeleteChannelMessageTool,
  microsoftTeamsDeleteChatMessageTool,
  microsoftTeamsGetMessageTool,
  microsoftTeamsListChannelMembersTool,
  microsoftTeamsListTeamMembersTool,
  microsoftTeamsReadChannelTool,
  microsoftTeamsReadChatTool,
  microsoftTeamsReplyToMessageTool,
  microsoftTeamsSetReactionTool,
  microsoftTeamsUnsetReactionTool,
  microsoftTeamsUpdateChannelMessageTool,
  microsoftTeamsUpdateChatMessageTool,
  microsoftTeamsWriteChannelTool,
  microsoftTeamsWriteChatTool,
} from '@/tools/microsoft_teams'
import { mistralParserTool } from '@/tools/mistral'
import {
  deleteTool as mongodbDeleteTool,
  executeTool as mongodbExecuteTool,
  insertTool as mongodbInsertTool,
  queryTool as mongodbQueryTool,
  updateTool as mongodbUpdateTool,
} from '@/tools/mongodb'
import {
  deleteTool as mysqlDeleteTool,
  executeTool as mysqlExecuteTool,
  insertTool as mysqlInsertTool,
  queryTool as mysqlQueryTool,
  updateTool as mysqlUpdateTool,
} from '@/tools/mysql'
import {
  notionCreateDatabaseTool,
  notionCreatePageTool,
  notionQueryDatabaseTool,
  notionReadDatabaseTool,
  notionReadTool,
  notionSearchTool,
  notionWriteTool,
} from '@/tools/notion'
import {
  onedriveCreateFolderTool,
  onedriveDeleteTool,
  onedriveDownloadTool,
  onedriveListTool,
  onedriveUploadTool,
} from '@/tools/onedrive'
import { imageTool, embeddingsTool as openAIEmbeddings } from '@/tools/openai'
import {
  outlookCopyTool,
  outlookDeleteTool,
  outlookDraftTool,
  outlookForwardTool,
  outlookMarkReadTool,
  outlookMarkUnreadTool,
  outlookMoveTool,
  outlookReadTool,
  outlookSendTool,
} from '@/tools/outlook'
import { parallelDeepResearchTool, parallelExtractTool, parallelSearchTool } from '@/tools/parallel'
import { perplexityChatTool, perplexitySearchTool } from '@/tools/perplexity'
import {
  pineconeFetchTool,
  pineconeGenerateEmbeddingsTool,
  pineconeSearchTextTool,
  pineconeSearchVectorTool,
  pineconeUpsertTextTool,
} from '@/tools/pinecone'
import {
  pipedriveCreateActivityTool,
  pipedriveCreateDealTool,
  pipedriveCreateLeadTool,
  pipedriveCreateProjectTool,
  pipedriveDeleteLeadTool,
  pipedriveGetActivitiesTool,
  pipedriveGetAllDealsTool,
  pipedriveGetDealTool,
  pipedriveGetFilesTool,
  pipedriveGetLeadsTool,
  pipedriveGetMailMessagesTool,
  pipedriveGetMailThreadTool,
  pipedriveGetPipelineDealsTool,
  pipedriveGetPipelinesTool,
  pipedriveGetProjectsTool,
  pipedriveUpdateActivityTool,
  pipedriveUpdateDealTool,
  pipedriveUpdateLeadTool,
} from '@/tools/pipedrive'
import {
  deleteTool as postgresDeleteTool,
  executeTool as postgresExecuteTool,
  insertTool as postgresInsertTool,
  queryTool as postgresQueryTool,
  updateTool as postgresUpdateTool,
} from '@/tools/postgresql'
import { qdrantFetchTool, qdrantSearchTool, qdrantUpsertTool } from '@/tools/qdrant'
import {
  redditDeleteTool,
  redditEditTool,
  redditGetCommentsTool,
  redditGetControversialTool,
  redditGetPostsTool,
  redditHotPostsTool,
  redditReplyTool,
  redditSaveTool,
  redditSearchTool,
  redditSubmitPostTool,
  redditSubscribeTool,
  redditUnsaveTool,
  redditVoteTool,
} from '@/tools/reddit'
import { mailSendTool } from '@/tools/resend'
import {
  s3CopyObjectTool,
  s3DeleteObjectTool,
  s3GetObjectTool,
  s3ListObjectsTool,
  s3PutObjectTool,
} from '@/tools/s3'
import {
  salesforceCreateAccountTool,
  salesforceCreateCaseTool,
  salesforceCreateContactTool,
  salesforceCreateLeadTool,
  salesforceCreateOpportunityTool,
  salesforceCreateTaskTool,
  salesforceDeleteAccountTool,
  salesforceDeleteCaseTool,
  salesforceDeleteContactTool,
  salesforceDeleteLeadTool,
  salesforceDeleteOpportunityTool,
  salesforceDeleteTaskTool,
  salesforceGetAccountsTool,
  salesforceGetCasesTool,
  salesforceGetContactsTool,
  salesforceGetLeadsTool,
  salesforceGetOpportunitiesTool,
  salesforceGetTasksTool,
  salesforceUpdateAccountTool,
  salesforceUpdateCaseTool,
  salesforceUpdateContactTool,
  salesforceUpdateLeadTool,
  salesforceUpdateOpportunityTool,
  salesforceUpdateTaskTool,
} from '@/tools/salesforce'
import { searchTool as serperSearch } from '@/tools/serper'
import {
  sharepointAddListItemTool,
  sharepointCreateListTool,
  sharepointCreatePageTool,
  sharepointGetListTool,
  sharepointListSitesTool,
  sharepointReadPageTool,
  sharepointUpdateListItemTool,
  sharepointUploadFileTool,
} from '@/tools/sharepoint'
import {
  slackAddReactionTool,
  slackCanvasTool,
  slackDeleteMessageTool,
  slackDownloadTool,
  slackMessageReaderTool,
  slackMessageTool,
  slackUpdateMessageTool,
} from '@/tools/slack'
import { smsSendTool } from '@/tools/sms'
import { stagehandAgentTool, stagehandExtractTool } from '@/tools/stagehand'
import {
  stripeCancelPaymentIntentTool,
  stripeCancelSubscriptionTool,
  stripeCaptureChargeTool,
  stripeCapturePaymentIntentTool,
  stripeConfirmPaymentIntentTool,
  stripeCreateChargeTool,
  stripeCreateCustomerTool,
  stripeCreateInvoiceTool,
  stripeCreatePaymentIntentTool,
  stripeCreatePriceTool,
  stripeCreateProductTool,
  stripeCreateSubscriptionTool,
  stripeDeleteCustomerTool,
  stripeDeleteInvoiceTool,
  stripeDeleteProductTool,
  stripeFinalizeInvoiceTool,
  stripeListChargesTool,
  stripeListCustomersTool,
  stripeListEventsTool,
  stripeListInvoicesTool,
  stripeListPaymentIntentsTool,
  stripeListPricesTool,
  stripeListProductsTool,
  stripeListSubscriptionsTool,
  stripePayInvoiceTool,
  stripeResumeSubscriptionTool,
  stripeRetrieveChargeTool,
  stripeRetrieveCustomerTool,
  stripeRetrieveEventTool,
  stripeRetrieveInvoiceTool,
  stripeRetrievePaymentIntentTool,
  stripeRetrievePriceTool,
  stripeRetrieveProductTool,
  stripeRetrieveSubscriptionTool,
  stripeSearchChargesTool,
  stripeSearchCustomersTool,
  stripeSearchInvoicesTool,
  stripeSearchPaymentIntentsTool,
  stripeSearchPricesTool,
  stripeSearchProductsTool,
  stripeSearchSubscriptionsTool,
  stripeSendInvoiceTool,
  stripeUpdateChargeTool,
  stripeUpdateCustomerTool,
  stripeUpdateInvoiceTool,
  stripeUpdatePaymentIntentTool,
  stripeUpdatePriceTool,
  stripeUpdateProductTool,
  stripeUpdateSubscriptionTool,
  stripeVoidInvoiceTool,
} from '@/tools/stripe'
import {
  supabaseCountTool,
  supabaseDeleteTool,
  supabaseGetRowTool,
  supabaseInsertTool,
  supabaseQueryTool,
  supabaseRpcTool,
  supabaseStorageCopyTool,
  supabaseStorageCreateBucketTool,
  supabaseStorageCreateSignedUrlTool,
  supabaseStorageDeleteBucketTool,
  supabaseStorageDeleteTool,
  supabaseStorageDownloadTool,
  supabaseStorageGetPublicUrlTool,
  supabaseStorageListBucketsTool,
  supabaseStorageListTool,
  supabaseStorageMoveTool,
  supabaseStorageUploadTool,
  supabaseTextSearchTool,
  supabaseUpdateTool,
  supabaseUpsertTool,
  supabaseVectorSearchTool,
} from '@/tools/supabase'
import { tavilyCrawlTool, tavilyExtractTool, tavilyMapTool, tavilySearchTool } from '@/tools/tavily'
import {
  telegramDeleteMessageTool,
  telegramMessageTool,
  telegramSendAnimationTool,
  telegramSendAudioTool,
  telegramSendDocumentTool,
  telegramSendPhotoTool,
  telegramSendVideoTool,
} from '@/tools/telegram'
import { thinkingTool } from '@/tools/thinking'
import {
  trelloAddCommentTool,
  trelloCreateCardTool,
  trelloGetActionsTool,
  trelloListCardsTool,
  trelloListListsTool,
  trelloUpdateCardTool,
} from '@/tools/trello'
import { sendSMSTool } from '@/tools/twilio'
import { getRecordingTool, listCallsTool, makeCallTool } from '@/tools/twilio_voice'
import {
  typeformCreateFormTool,
  typeformDeleteFormTool,
  typeformFilesTool,
  typeformGetFormTool,
  typeformInsightsTool,
  typeformListFormsTool,
  typeformResponsesTool,
  typeformUpdateFormTool,
} from '@/tools/typeform'
import type { ToolConfig } from '@/tools/types'
import { visionTool } from '@/tools/vision'
import {
  wealthboxReadContactTool,
  wealthboxReadNoteTool,
  wealthboxReadTaskTool,
  wealthboxWriteContactTool,
  wealthboxWriteNoteTool,
  wealthboxWriteTaskTool,
} from '@/tools/wealthbox'
import {
  webflowCreateItemTool,
  webflowDeleteItemTool,
  webflowGetItemTool,
  webflowListItemsTool,
  webflowUpdateItemTool,
} from '@/tools/webflow'
import { whatsappSendMessageTool } from '@/tools/whatsapp'
import {
  wikipediaPageContentTool,
  wikipediaPageSummaryTool,
  wikipediaRandomPageTool,
  wikipediaSearchTool,
} from '@/tools/wikipedia'
import { workflowExecutorTool } from '@/tools/workflow'
import { xReadTool, xSearchTool, xUserTool, xWriteTool } from '@/tools/x'
import {
  youtubeChannelInfoTool,
  youtubeChannelPlaylistsTool,
  youtubeChannelVideosTool,
  youtubeCommentsTool,
  youtubePlaylistItemsTool,
  youtubeRelatedVideosTool,
  youtubeSearchTool,
  youtubeVideoDetailsTool,
} from '@/tools/youtube'
import {
  zepAddMessagesTool,
  zepAddUserTool,
  zepCreateThreadTool,
  zepDeleteThreadTool,
  zepGetContextTool,
  zepGetMessagesTool,
  zepGetThreadsTool,
  zepGetUserThreadsTool,
  zepGetUserTool,
} from '@/tools/zep'

// Registry of all available tools
export const tools: Record<string, ToolConfig> = {
  arxiv_search: arxivSearchTool,
  arxiv_get_paper: arxivGetPaperTool,
  arxiv_get_author_papers: arxivGetAuthorPapersTool,
  asana_get_task: asanaGetTaskTool,
  asana_create_task: asanaCreateTaskTool,
  asana_update_task: asanaUpdateTaskTool,
  asana_get_projects: asanaGetProjectsTool,
  asana_search_tasks: asanaSearchTasksTool,
  asana_add_comment: asanaAddCommentTool,
  browser_use_run_task: browserUseRunTaskTool,
  openai_embeddings: openAIEmbeddings,
  http_request: httpRequest,
  huggingface_chat: huggingfaceChatTool,
  function_execute: functionExecuteTool,
  vision_tool: visionTool,
  file_parser: fileParseTool,
  firecrawl_scrape: scrapeTool,
  firecrawl_search: searchTool,
  firecrawl_crawl: crawlTool,
  firecrawl_map: mapTool,
  firecrawl_extract: extractTool,
  google_search: googleSearchTool,
  guardrails_validate: guardrailsValidateTool,
  jina_read_url: readUrlTool,
  jina_search: jinaSearchTool,
  linkup_search: linkupSearchTool,
  resend_send: mailSendTool,
  sms_send: smsSendTool,
  jira_retrieve: jiraRetrieveTool,
  jira_update: jiraUpdateTool,
  jira_write: jiraWriteTool,
  jira_bulk_read: jiraBulkRetrieveTool,
  jira_delete_issue: jiraDeleteIssueTool,
  jira_assign_issue: jiraAssignIssueTool,
  jira_transition_issue: jiraTransitionIssueTool,
  jira_search_issues: jiraSearchIssuesTool,
  jira_add_comment: jiraAddCommentTool,
  jira_get_comments: jiraGetCommentsTool,
  jira_update_comment: jiraUpdateCommentTool,
  jira_delete_comment: jiraDeleteCommentTool,
  jira_get_attachments: jiraGetAttachmentsTool,
  jira_delete_attachment: jiraDeleteAttachmentTool,
  jira_add_worklog: jiraAddWorklogTool,
  jira_get_worklogs: jiraGetWorklogsTool,
  jira_update_worklog: jiraUpdateWorklogTool,
  jira_delete_worklog: jiraDeleteWorklogTool,
  jira_create_issue_link: jiraCreateIssueLinkTool,
  jira_delete_issue_link: jiraDeleteIssueLinkTool,
  jira_add_watcher: jiraAddWatcherTool,
  jira_remove_watcher: jiraRemoveWatcherTool,
  slack_message: slackMessageTool,
  slack_message_reader: slackMessageReaderTool,
  slack_canvas: slackCanvasTool,
  slack_download: slackDownloadTool,
  slack_update_message: slackUpdateMessageTool,
  slack_delete_message: slackDeleteMessageTool,
  slack_add_reaction: slackAddReactionTool,
  github_repo_info: githubRepoInfoTool,
  github_latest_commit: githubLatestCommitTool,
  serper_search: serperSearch,
  tavily_search: tavilySearchTool,
  tavily_extract: tavilyExtractTool,
  tavily_crawl: tavilyCrawlTool,
  tavily_map: tavilyMapTool,
  supabase_query: supabaseQueryTool,
  supabase_insert: supabaseInsertTool,
  supabase_get_row: supabaseGetRowTool,
  supabase_update: supabaseUpdateTool,
  supabase_delete: supabaseDeleteTool,
  supabase_upsert: supabaseUpsertTool,
  supabase_count: supabaseCountTool,
  supabase_text_search: supabaseTextSearchTool,
  supabase_vector_search: supabaseVectorSearchTool,
  supabase_rpc: supabaseRpcTool,
  supabase_storage_upload: supabaseStorageUploadTool,
  supabase_storage_download: supabaseStorageDownloadTool,
  supabase_storage_list: supabaseStorageListTool,
  supabase_storage_delete: supabaseStorageDeleteTool,
  supabase_storage_move: supabaseStorageMoveTool,
  supabase_storage_copy: supabaseStorageCopyTool,
  supabase_storage_create_bucket: supabaseStorageCreateBucketTool,
  supabase_storage_list_buckets: supabaseStorageListBucketsTool,
  supabase_storage_delete_bucket: supabaseStorageDeleteBucketTool,
  supabase_storage_get_public_url: supabaseStorageGetPublicUrlTool,
  supabase_storage_create_signed_url: supabaseStorageCreateSignedUrlTool,
  typeform_responses: typeformResponsesTool,
  typeform_files: typeformFilesTool,
  typeform_insights: typeformInsightsTool,
  typeform_list_forms: typeformListFormsTool,
  typeform_get_form: typeformGetFormTool,
  typeform_create_form: typeformCreateFormTool,
  typeform_update_form: typeformUpdateFormTool,
  typeform_delete_form: typeformDeleteFormTool,
  youtube_search: youtubeSearchTool,
  youtube_video_details: youtubeVideoDetailsTool,
  youtube_channel_info: youtubeChannelInfoTool,
  youtube_playlist_items: youtubePlaylistItemsTool,
  youtube_comments: youtubeCommentsTool,
  youtube_channel_videos: youtubeChannelVideosTool,
  youtube_channel_playlists: youtubeChannelPlaylistsTool,
  youtube_related_videos: youtubeRelatedVideosTool,
  notion_read: notionReadTool,
  notion_read_database: notionReadDatabaseTool,
  notion_write: notionWriteTool,
  notion_create_page: notionCreatePageTool,
  notion_query_database: notionQueryDatabaseTool,
  notion_search: notionSearchTool,
  notion_create_database: notionCreateDatabaseTool,
  gmail_send: gmailSendTool,
  gmail_read: gmailReadTool,
  gmail_search: gmailSearchTool,
  gmail_draft: gmailDraftTool,
  gmail_move: gmailMoveTool,
  gmail_mark_read: gmailMarkReadTool,
  gmail_mark_unread: gmailMarkUnreadTool,
  gmail_archive: gmailArchiveTool,
  gmail_unarchive: gmailUnarchiveTool,
  gmail_delete: gmailDeleteTool,
  gmail_add_label: gmailAddLabelTool,
  gmail_remove_label: gmailRemoveLabelTool,
  whatsapp_send_message: whatsappSendMessageTool,
  x_write: xWriteTool,
  x_read: xReadTool,
  x_search: xSearchTool,
  x_user: xUserTool,
  pinecone_fetch: pineconeFetchTool,
  pinecone_generate_embeddings: pineconeGenerateEmbeddingsTool,
  pinecone_search_text: pineconeSearchTextTool,
  pinecone_search_vector: pineconeSearchVectorTool,
  pinecone_upsert_text: pineconeUpsertTextTool,
  pipedrive_create_activity: pipedriveCreateActivityTool,
  pipedrive_create_deal: pipedriveCreateDealTool,
  pipedrive_create_lead: pipedriveCreateLeadTool,
  pipedrive_create_project: pipedriveCreateProjectTool,
  pipedrive_delete_lead: pipedriveDeleteLeadTool,
  pipedrive_get_activities: pipedriveGetActivitiesTool,
  pipedrive_get_all_deals: pipedriveGetAllDealsTool,
  pipedrive_get_deal: pipedriveGetDealTool,
  pipedrive_get_files: pipedriveGetFilesTool,
  pipedrive_get_leads: pipedriveGetLeadsTool,
  pipedrive_get_mail_messages: pipedriveGetMailMessagesTool,
  pipedrive_get_mail_thread: pipedriveGetMailThreadTool,
  pipedrive_get_pipeline_deals: pipedriveGetPipelineDealsTool,
  pipedrive_get_pipelines: pipedriveGetPipelinesTool,
  pipedrive_get_projects: pipedriveGetProjectsTool,
  pipedrive_update_activity: pipedriveUpdateActivityTool,
  pipedrive_update_deal: pipedriveUpdateDealTool,
  pipedrive_update_lead: pipedriveUpdateLeadTool,
  postgresql_query: postgresQueryTool,
  postgresql_insert: postgresInsertTool,
  postgresql_update: postgresUpdateTool,
  postgresql_delete: postgresDeleteTool,
  postgresql_execute: postgresExecuteTool,
  mongodb_query: mongodbQueryTool,
  mongodb_insert: mongodbInsertTool,
  mongodb_update: mongodbUpdateTool,
  mongodb_delete: mongodbDeleteTool,
  mongodb_execute: mongodbExecuteTool,
  mysql_query: mysqlQueryTool,
  mysql_insert: mysqlInsertTool,
  mysql_update: mysqlUpdateTool,
  mysql_delete: mysqlDeleteTool,
  mysql_execute: mysqlExecuteTool,
  github_pr: githubPrTool,
  github_comment: githubCommentTool,
  github_issue_comment: githubIssueCommentTool,
  github_list_issue_comments: githubListIssueCommentsTool,
  github_update_comment: githubUpdateCommentTool,
  github_delete_comment: githubDeleteCommentTool,
  github_list_pr_comments: githubListPRCommentsTool,
  github_create_pr: githubCreatePRTool,
  github_update_pr: githubUpdatePRTool,
  github_merge_pr: githubMergePRTool,
  github_list_prs: githubListPRsTool,
  github_get_pr_files: githubGetPRFilesTool,
  github_close_pr: githubClosePRTool,
  github_request_reviewers: githubRequestReviewersTool,
  github_get_file_content: githubGetFileContentTool,
  github_create_file: githubCreateFileTool,
  github_update_file: githubUpdateFileTool,
  github_delete_file: githubDeleteFileTool,
  github_get_tree: githubGetTreeTool,
  github_list_branches: githubListBranchesTool,
  github_get_branch: githubGetBranchTool,
  github_create_branch: githubCreateBranchTool,
  github_delete_branch: githubDeleteBranchTool,
  github_get_branch_protection: githubGetBranchProtectionTool,
  github_update_branch_protection: githubUpdateBranchProtectionTool,
  github_create_issue: githubCreateIssueTool,
  github_update_issue: githubUpdateIssueTool,
  github_list_issues: githubListIssuesTool,
  github_get_issue: githubGetIssueTool,
  github_close_issue: githubCloseIssueTool,
  github_add_labels: githubAddLabelsTool,
  github_remove_label: githubRemoveLabelTool,
  github_add_assignees: githubAddAssigneesTool,
  github_create_release: githubCreateReleaseTool,
  github_update_release: githubUpdateReleaseTool,
  github_list_releases: githubListReleasesTool,
  github_get_release: githubGetReleaseTool,
  github_delete_release: githubDeleteReleaseTool,
  github_list_workflows: githubListWorkflowsTool,
  github_get_workflow: githubGetWorkflowTool,
  github_trigger_workflow: githubTriggerWorkflowTool,
  github_list_workflow_runs: githubListWorkflowRunsTool,
  github_get_workflow_run: githubGetWorkflowRunTool,
  github_cancel_workflow_run: githubCancelWorkflowRunTool,
  github_rerun_workflow: githubRerunWorkflowTool,
  github_list_projects: githubListProjectsTool,
  github_get_project: githubGetProjectTool,
  github_create_project: githubCreateProjectTool,
  github_update_project: githubUpdateProjectTool,
  github_delete_project: githubDeleteProjectTool,
  exa_search: exaSearchTool,
  exa_get_contents: exaGetContentsTool,
  exa_find_similar_links: exaFindSimilarLinksTool,
  exa_answer: exaAnswerTool,
  exa_research: exaResearchTool,
  parallel_search: parallelSearchTool,
  parallel_extract: parallelExtractTool,
  parallel_deep_research: parallelDeepResearchTool,
  reddit_hot_posts: redditHotPostsTool,
  reddit_get_posts: redditGetPostsTool,
  reddit_get_comments: redditGetCommentsTool,
  reddit_get_controversial: redditGetControversialTool,
  reddit_search: redditSearchTool,
  reddit_submit_post: redditSubmitPostTool,
  reddit_vote: redditVoteTool,
  reddit_save: redditSaveTool,
  reddit_unsave: redditUnsaveTool,
  reddit_reply: redditReplyTool,
  reddit_edit: redditEditTool,
  reddit_delete: redditDeleteTool,
  reddit_subscribe: redditSubscribeTool,
  google_drive_get_content: googleDriveGetContentTool,
  google_drive_list: googleDriveListTool,
  google_drive_upload: googleDriveUploadTool,
  google_drive_download: googleDriveDownloadTool,
  google_drive_create_folder: googleDriveCreateFolderTool,
  google_docs_read: googleDocsReadTool,
  google_docs_write: googleDocsWriteTool,
  google_docs_create: googleDocsCreateTool,
  google_sheets_read: googleSheetsReadTool,
  google_sheets_write: googleSheetsWriteTool,
  google_sheets_update: googleSheetsUpdateTool,
  google_sheets_append: googleSheetsAppendTool,
  perplexity_chat: perplexityChatTool,
  perplexity_search: perplexitySearchTool,
  confluence_retrieve: confluenceRetrieveTool,
  confluence_update: confluenceUpdateTool,
  confluence_create_page: confluenceCreatePageTool,
  confluence_delete_page: confluenceDeletePageTool,
  confluence_search: confluenceSearchTool,
  confluence_create_comment: confluenceCreateCommentTool,
  confluence_list_comments: confluenceListCommentsTool,
  confluence_update_comment: confluenceUpdateCommentTool,
  confluence_delete_comment: confluenceDeleteCommentTool,
  confluence_list_attachments: confluenceListAttachmentsTool,
  confluence_delete_attachment: confluenceDeleteAttachmentTool,
  confluence_list_labels: confluenceListLabelsTool,
  confluence_get_space: confluenceGetSpaceTool,
  confluence_list_spaces: confluenceListSpacesTool,
  trello_list_lists: trelloListListsTool,
  trello_list_cards: trelloListCardsTool,
  trello_create_card: trelloCreateCardTool,
  trello_update_card: trelloUpdateCardTool,
  trello_get_actions: trelloGetActionsTool,
  trello_add_comment: trelloAddCommentTool,
  twilio_send_sms: sendSMSTool,
  twilio_voice_make_call: makeCallTool,
  twilio_voice_list_calls: listCallsTool,
  twilio_voice_get_recording: getRecordingTool,
  airtable_create_records: airtableCreateRecordsTool,
  airtable_get_record: airtableGetRecordTool,
  airtable_list_records: airtableListRecordsTool,
  airtable_update_record: airtableUpdateRecordTool,
  mistral_parser: mistralParserTool,
  thinking_tool: thinkingTool,
  stagehand_extract: stagehandExtractTool,
  stagehand_agent: stagehandAgentTool,
  mem0_add_memories: mem0AddMemoriesTool,
  mem0_search_memories: mem0SearchMemoriesTool,
  mem0_get_memories: mem0GetMemoriesTool,
  zep_create_thread: zepCreateThreadTool,
  zep_get_threads: zepGetThreadsTool,
  zep_delete_thread: zepDeleteThreadTool,
  zep_get_context: zepGetContextTool,
  zep_get_messages: zepGetMessagesTool,
  zep_add_messages: zepAddMessagesTool,
  zep_add_user: zepAddUserTool,
  zep_get_user: zepGetUserTool,
  zep_get_user_threads: zepGetUserThreadsTool,
  memory_add: memoryAddTool,
  memory_get: memoryGetTool,
  memory_get_all: memoryGetAllTool,
  memory_delete: memoryDeleteTool,
  knowledge_search: knowledgeSearchTool,
  knowledge_upload_chunk: knowledgeUploadChunkTool,
  knowledge_create_document: knowledgeCreateDocumentTool,
  elevenlabs_tts: elevenLabsTtsTool,
  s3_get_object: s3GetObjectTool,
  s3_put_object: s3PutObjectTool,
  s3_list_objects: s3ListObjectsTool,
  s3_delete_object: s3DeleteObjectTool,
  s3_copy_object: s3CopyObjectTool,
  telegram_message: telegramMessageTool,
  telegram_delete_message: telegramDeleteMessageTool,
  telegram_send_audio: telegramSendAudioTool,
  telegram_send_animation: telegramSendAnimationTool,
  telegram_send_photo: telegramSendPhotoTool,
  telegram_send_video: telegramSendVideoTool,
  telegram_send_document: telegramSendDocumentTool,
  clay_populate: clayPopulateTool,
  discord_send_message: discordSendMessageTool,
  discord_get_messages: discordGetMessagesTool,
  discord_get_server: discordGetServerTool,
  discord_get_user: discordGetUserTool,
  discord_edit_message: discordEditMessageTool,
  discord_delete_message: discordDeleteMessageTool,
  discord_add_reaction: discordAddReactionTool,
  discord_remove_reaction: discordRemoveReactionTool,
  discord_pin_message: discordPinMessageTool,
  discord_unpin_message: discordUnpinMessageTool,
  discord_create_thread: discordCreateThreadTool,
  discord_join_thread: discordJoinThreadTool,
  discord_leave_thread: discordLeaveThreadTool,
  discord_archive_thread: discordArchiveThreadTool,
  discord_create_channel: discordCreateChannelTool,
  discord_update_channel: discordUpdateChannelTool,
  discord_delete_channel: discordDeleteChannelTool,
  discord_get_channel: discordGetChannelTool,
  discord_create_role: discordCreateRoleTool,
  discord_update_role: discordUpdateRoleTool,
  discord_delete_role: discordDeleteRoleTool,
  discord_assign_role: discordAssignRoleTool,
  discord_remove_role: discordRemoveRoleTool,
  discord_kick_member: discordKickMemberTool,
  discord_ban_member: discordBanMemberTool,
  discord_unban_member: discordUnbanMemberTool,
  discord_get_member: discordGetMemberTool,
  discord_update_member: discordUpdateMemberTool,
  discord_create_invite: discordCreateInviteTool,
  discord_get_invite: discordGetInviteTool,
  discord_delete_invite: discordDeleteInviteTool,
  discord_create_webhook: discordCreateWebhookTool,
  discord_execute_webhook: discordExecuteWebhookTool,
  discord_get_webhook: discordGetWebhookTool,
  discord_delete_webhook: discordDeleteWebhookTool,
  openai_image: imageTool,
  microsoft_teams_read_chat: microsoftTeamsReadChatTool,
  microsoft_teams_write_chat: microsoftTeamsWriteChatTool,
  microsoft_teams_read_channel: microsoftTeamsReadChannelTool,
  microsoft_teams_write_channel: microsoftTeamsWriteChannelTool,
  microsoft_teams_update_chat_message: microsoftTeamsUpdateChatMessageTool,
  microsoft_teams_update_channel_message: microsoftTeamsUpdateChannelMessageTool,
  microsoft_teams_delete_chat_message: microsoftTeamsDeleteChatMessageTool,
  microsoft_teams_delete_channel_message: microsoftTeamsDeleteChannelMessageTool,
  microsoft_teams_reply_to_message: microsoftTeamsReplyToMessageTool,
  microsoft_teams_set_reaction: microsoftTeamsSetReactionTool,
  microsoft_teams_unset_reaction: microsoftTeamsUnsetReactionTool,
  microsoft_teams_get_message: microsoftTeamsGetMessageTool,
  microsoft_teams_list_team_members: microsoftTeamsListTeamMembersTool,
  microsoft_teams_list_channel_members: microsoftTeamsListChannelMembersTool,
  outlook_read: outlookReadTool,
  outlook_send: outlookSendTool,
  outlook_draft: outlookDraftTool,
  outlook_forward: outlookForwardTool,
  outlook_move: outlookMoveTool,
  outlook_mark_read: outlookMarkReadTool,
  outlook_mark_unread: outlookMarkUnreadTool,
  outlook_delete: outlookDeleteTool,
  outlook_copy: outlookCopyTool,
  linear_read_issues: linearReadIssuesTool,
  linear_create_issue: linearCreateIssueTool,
  linear_get_issue: linearGetIssueTool,
  linear_update_issue: linearUpdateIssueTool,
  linear_archive_issue: linearArchiveIssueTool,
  linear_unarchive_issue: linearUnarchiveIssueTool,
  linear_delete_issue: linearDeleteIssueTool,
  linear_add_label_to_issue: linearAddLabelToIssueTool,
  linear_remove_label_from_issue: linearRemoveLabelFromIssueTool,
  linear_search_issues: linearSearchIssuesTool,
  linear_create_comment: linearCreateCommentTool,
  linear_update_comment: linearUpdateCommentTool,
  linear_delete_comment: linearDeleteCommentTool,
  linear_list_comments: linearListCommentsTool,
  linear_list_projects: linearListProjectsTool,
  linear_get_project: linearGetProjectTool,
  linear_create_project: linearCreateProjectTool,
  linear_update_project: linearUpdateProjectTool,
  linear_archive_project: linearArchiveProjectTool,
  linear_list_users: linearListUsersTool,
  linear_list_teams: linearListTeamsTool,
  linear_get_viewer: linearGetViewerTool,
  linear_list_labels: linearListLabelsTool,
  linear_create_label: linearCreateLabelTool,
  linear_update_label: linearUpdateLabelTool,
  linear_archive_label: linearArchiveLabelTool,
  linear_list_workflow_states: linearListWorkflowStatesTool,
  linear_create_workflow_state: linearCreateWorkflowStateTool,
  linear_update_workflow_state: linearUpdateWorkflowStateTool,
  linear_list_cycles: linearListCyclesTool,
  linear_get_cycle: linearGetCycleTool,
  linear_create_cycle: linearCreateCycleTool,
  linear_get_active_cycle: linearGetActiveCycleTool,
  linear_create_attachment: linearCreateAttachmentTool,
  linear_list_attachments: linearListAttachmentsTool,
  linear_update_attachment: linearUpdateAttachmentTool,
  linear_delete_attachment: linearDeleteAttachmentTool,
  linear_create_issue_relation: linearCreateIssueRelationTool,
  linear_list_issue_relations: linearListIssueRelationsTool,
  linear_delete_issue_relation: linearDeleteIssueRelationTool,
  linear_create_favorite: linearCreateFavoriteTool,
  linear_list_favorites: linearListFavoritesTool,
  linear_create_project_update: linearCreateProjectUpdateTool,
  linear_list_project_updates: linearListProjectUpdatesTool,
  linear_create_project_link: linearCreateProjectLinkTool,
  linear_list_notifications: linearListNotificationsTool,
  linear_update_notification: linearUpdateNotificationTool,
  linear_create_customer: linearCreateCustomerTool,
  linear_list_customers: linearListCustomersTool,
  linear_create_customer_request: linearCreateCustomerRequestTool,
  linear_update_customer_request: linearUpdateCustomerRequestTool,
  linear_list_customer_requests: linearListCustomerRequestsTool,
  linear_get_customer: linearGetCustomerTool,
  linear_update_customer: linearUpdateCustomerTool,
  linear_delete_customer: linearDeleteCustomerTool,
  linear_merge_customers: linearMergeCustomersTool,
  linear_create_customer_status: linearCreateCustomerStatusTool,
  linear_update_customer_status: linearUpdateCustomerStatusTool,
  linear_delete_customer_status: linearDeleteCustomerStatusTool,
  linear_list_customer_statuses: linearListCustomerStatusesTool,
  linear_create_customer_tier: linearCreateCustomerTierTool,
  linear_update_customer_tier: linearUpdateCustomerTierTool,
  linear_delete_customer_tier: linearDeleteCustomerTierTool,
  linear_list_customer_tiers: linearListCustomerTiersTool,
  linear_delete_project: linearDeleteProjectTool,
  linear_create_project_label: linearCreateProjectLabelTool,
  linear_update_project_label: linearUpdateProjectLabelTool,
  linear_delete_project_label: linearDeleteProjectLabelTool,
  linear_list_project_labels: linearListProjectLabelsTool,
  linear_add_label_to_project: linearAddLabelToProjectTool,
  linear_remove_label_from_project: linearRemoveLabelFromProjectTool,
  linear_create_project_milestone: linearCreateProjectMilestoneTool,
  linear_update_project_milestone: linearUpdateProjectMilestoneTool,
  linear_delete_project_milestone: linearDeleteProjectMilestoneTool,
  linear_list_project_milestones: linearListProjectMilestonesTool,
  linear_create_project_status: linearCreateProjectStatusTool,
  linear_update_project_status: linearUpdateProjectStatusTool,
  linear_delete_project_status: linearDeleteProjectStatusTool,
  linear_list_project_statuses: linearListProjectStatusesTool,
  onedrive_create_folder: onedriveCreateFolderTool,
  onedrive_delete: onedriveDeleteTool,
  onedrive_download: onedriveDownloadTool,
  onedrive_list: onedriveListTool,
  onedrive_upload: onedriveUploadTool,
  microsoft_excel_read: microsoftExcelReadTool,
  microsoft_excel_write: microsoftExcelWriteTool,
  microsoft_excel_table_add: microsoftExcelTableAddTool,
  microsoft_planner_create_task: microsoftPlannerCreateTaskTool,
  microsoft_planner_read_task: microsoftPlannerReadTaskTool,
  microsoft_planner_update_task: microsoftPlannerUpdateTaskTool,
  microsoft_planner_delete_task: microsoftPlannerDeleteTaskTool,
  microsoft_planner_list_plans: microsoftPlannerListPlansTool,
  microsoft_planner_read_plan: microsoftPlannerReadPlanTool,
  microsoft_planner_list_buckets: microsoftPlannerListBucketsTool,
  microsoft_planner_read_bucket: microsoftPlannerReadBucketTool,
  microsoft_planner_create_bucket: microsoftPlannerCreateBucketTool,
  microsoft_planner_update_bucket: microsoftPlannerUpdateBucketTool,
  microsoft_planner_delete_bucket: microsoftPlannerDeleteBucketTool,
  microsoft_planner_get_task_details: microsoftPlannerGetTaskDetailsTool,
  microsoft_planner_update_task_details: microsoftPlannerUpdateTaskDetailsTool,
  google_calendar_create: googleCalendarCreateTool,
  google_calendar_get: googleCalendarGetTool,
  google_calendar_list: googleCalendarListTool,
  google_calendar_quick_add: googleCalendarQuickAddTool,
  google_calendar_invite: googleCalendarInviteTool,
  google_forms_get_responses: googleFormsGetResponsesTool,
  workflow_executor: workflowExecutorTool,
  wealthbox_read_contact: wealthboxReadContactTool,
  wealthbox_write_contact: wealthboxWriteContactTool,
  wealthbox_read_task: wealthboxReadTaskTool,
  wealthbox_write_task: wealthboxWriteTaskTool,
  wealthbox_read_note: wealthboxReadNoteTool,
  wealthbox_write_note: wealthboxWriteNoteTool,
  webflow_list_items: webflowListItemsTool,
  webflow_get_item: webflowGetItemTool,
  webflow_create_item: webflowCreateItemTool,
  webflow_update_item: webflowUpdateItemTool,
  webflow_delete_item: webflowDeleteItemTool,
  wikipedia_summary: wikipediaPageSummaryTool,
  wikipedia_search: wikipediaSearchTool,
  wikipedia_content: wikipediaPageContentTool,
  wikipedia_random: wikipediaRandomPageTool,
  google_vault_create_matters_export: createMattersExportTool,
  google_vault_list_matters_export: listMattersExportTool,
  google_vault_create_matters_holds: createMattersHoldsTool,
  google_vault_list_matters_holds: listMattersHoldsTool,
  google_vault_create_matters: createMattersTool,
  google_vault_list_matters: listMattersTool,
  google_vault_download_export_file: downloadExportFileTool,
  qdrant_fetch_points: qdrantFetchTool,
  qdrant_search_vector: qdrantSearchTool,
  qdrant_upsert_points: qdrantUpsertTool,
  hunter_discover: hunterDiscoverTool,
  hunter_domain_search: hunterDomainSearchTool,
  hunter_email_finder: hunterEmailFinderTool,
  hunter_email_verifier: hunterEmailVerifierTool,
  hunter_companies_find: hunterCompaniesFindTool,
  hunter_email_count: hunterEmailCountTool,
  hubspot_create_company: hubspotCreateCompanyTool,
  hubspot_create_contact: hubspotCreateContactTool,
  hubspot_get_company: hubspotGetCompanyTool,
  hubspot_get_contact: hubspotGetContactTool,
  hubspot_get_users: hubspotGetUsersTool,
  hubspot_list_companies: hubspotListCompaniesTool,
  hubspot_list_contacts: hubspotListContactsTool,
  hubspot_list_deals: hubspotListDealsTool,
  hubspot_search_companies: hubspotSearchCompaniesTool,
  hubspot_search_contacts: hubspotSearchContactsTool,
  hubspot_update_company: hubspotUpdateCompanyTool,
  hubspot_update_contact: hubspotUpdateContactTool,
  sharepoint_create_page: sharepointCreatePageTool,
  sharepoint_read_page: sharepointReadPageTool,
  sharepoint_list_sites: sharepointListSitesTool,
  sharepoint_get_list: sharepointGetListTool,
  sharepoint_create_list: sharepointCreateListTool,
  sharepoint_update_list: sharepointUpdateListItemTool,
  sharepoint_add_list_items: sharepointAddListItemTool,
  sharepoint_upload_file: sharepointUploadFileTool,
  stripe_create_payment_intent: stripeCreatePaymentIntentTool,
  stripe_retrieve_payment_intent: stripeRetrievePaymentIntentTool,
  stripe_update_payment_intent: stripeUpdatePaymentIntentTool,
  stripe_confirm_payment_intent: stripeConfirmPaymentIntentTool,
  stripe_capture_payment_intent: stripeCapturePaymentIntentTool,
  stripe_cancel_payment_intent: stripeCancelPaymentIntentTool,
  stripe_list_payment_intents: stripeListPaymentIntentsTool,
  stripe_search_payment_intents: stripeSearchPaymentIntentsTool,
  stripe_create_customer: stripeCreateCustomerTool,
  stripe_retrieve_customer: stripeRetrieveCustomerTool,
  stripe_update_customer: stripeUpdateCustomerTool,
  stripe_delete_customer: stripeDeleteCustomerTool,
  stripe_list_customers: stripeListCustomersTool,
  stripe_search_customers: stripeSearchCustomersTool,
  stripe_create_subscription: stripeCreateSubscriptionTool,
  stripe_retrieve_subscription: stripeRetrieveSubscriptionTool,
  stripe_update_subscription: stripeUpdateSubscriptionTool,
  stripe_cancel_subscription: stripeCancelSubscriptionTool,
  stripe_resume_subscription: stripeResumeSubscriptionTool,
  stripe_list_subscriptions: stripeListSubscriptionsTool,
  stripe_search_subscriptions: stripeSearchSubscriptionsTool,
  stripe_create_invoice: stripeCreateInvoiceTool,
  stripe_retrieve_invoice: stripeRetrieveInvoiceTool,
  stripe_update_invoice: stripeUpdateInvoiceTool,
  stripe_delete_invoice: stripeDeleteInvoiceTool,
  stripe_finalize_invoice: stripeFinalizeInvoiceTool,
  stripe_pay_invoice: stripePayInvoiceTool,
  stripe_void_invoice: stripeVoidInvoiceTool,
  stripe_send_invoice: stripeSendInvoiceTool,
  stripe_list_invoices: stripeListInvoicesTool,
  stripe_search_invoices: stripeSearchInvoicesTool,
  stripe_create_charge: stripeCreateChargeTool,
  stripe_retrieve_charge: stripeRetrieveChargeTool,
  stripe_update_charge: stripeUpdateChargeTool,
  stripe_capture_charge: stripeCaptureChargeTool,
  stripe_list_charges: stripeListChargesTool,
  stripe_search_charges: stripeSearchChargesTool,
  stripe_create_product: stripeCreateProductTool,
  stripe_retrieve_product: stripeRetrieveProductTool,
  stripe_update_product: stripeUpdateProductTool,
  stripe_delete_product: stripeDeleteProductTool,
  stripe_list_products: stripeListProductsTool,
  stripe_search_products: stripeSearchProductsTool,
  stripe_create_price: stripeCreatePriceTool,
  stripe_retrieve_price: stripeRetrievePriceTool,
  stripe_update_price: stripeUpdatePriceTool,
  stripe_list_prices: stripeListPricesTool,
  stripe_search_prices: stripeSearchPricesTool,
  stripe_retrieve_event: stripeRetrieveEventTool,
  stripe_list_events: stripeListEventsTool,
  salesforce_get_accounts: salesforceGetAccountsTool,
  salesforce_create_account: salesforceCreateAccountTool,
  salesforce_update_account: salesforceUpdateAccountTool,
  salesforce_delete_account: salesforceDeleteAccountTool,
  salesforce_get_contacts: salesforceGetContactsTool,
  salesforce_create_contact: salesforceCreateContactTool,
  salesforce_update_contact: salesforceUpdateContactTool,
  salesforce_delete_contact: salesforceDeleteContactTool,
  salesforce_get_leads: salesforceGetLeadsTool,
  salesforce_create_lead: salesforceCreateLeadTool,
  salesforce_update_lead: salesforceUpdateLeadTool,
  salesforce_delete_lead: salesforceDeleteLeadTool,
  salesforce_get_opportunities: salesforceGetOpportunitiesTool,
  salesforce_create_opportunity: salesforceCreateOpportunityTool,
  salesforce_update_opportunity: salesforceUpdateOpportunityTool,
  salesforce_delete_opportunity: salesforceDeleteOpportunityTool,
  salesforce_get_cases: salesforceGetCasesTool,
  salesforce_create_case: salesforceCreateCaseTool,
  salesforce_update_case: salesforceUpdateCaseTool,
  salesforce_delete_case: salesforceDeleteCaseTool,
  salesforce_get_tasks: salesforceGetTasksTool,
  salesforce_create_task: salesforceCreateTaskTool,
  salesforce_update_task: salesforceUpdateTaskTool,
  salesforce_delete_task: salesforceDeleteTaskTool,
}
