import { GoogleTranslateIcon } from '@/components/icons'
import { AuthMode, type BlockConfig } from '@/blocks/types'

export const GoogleTranslateBlock: BlockConfig = {
  type: 'google_translate',
  name: 'Google Translate',
  description: 'Translate text using Google Cloud Translation',
  longDescription:
    'Translate and detect languages using the Google Cloud Translation API. Supports auto-detection of the source language.',
  docsLink: 'https://docs.sim.ai/tools/google_translate',
  category: 'tools',
  bgColor: '#E0E0E0',
  icon: GoogleTranslateIcon,
  authMode: AuthMode.ApiKey,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      options: [
        { label: 'Translate Text', id: 'text' },
        { label: 'Detect Language', id: 'detect' },
      ],
      value: () => 'text',
    },
    {
      id: 'text',
      title: 'Text',
      type: 'long-input',
      placeholder: 'Enter text...',
      required: true,
    },
    {
      id: 'target',
      title: 'Target Language',
      type: 'dropdown',
      condition: { field: 'operation', value: 'text' },
      options: [
        { label: 'English', id: 'en' },
        { label: 'Spanish', id: 'es' },
        { label: 'French', id: 'fr' },
        { label: 'German', id: 'de' },
        { label: 'Italian', id: 'it' },
        { label: 'Portuguese', id: 'pt' },
        { label: 'Russian', id: 'ru' },
        { label: 'Japanese', id: 'ja' },
        { label: 'Korean', id: 'ko' },
        { label: 'Chinese (Simplified)', id: 'zh-CN' },
        { label: 'Chinese (Traditional)', id: 'zh-TW' },
        { label: 'Arabic', id: 'ar' },
        { label: 'Hindi', id: 'hi' },
        { label: 'Turkish', id: 'tr' },
        { label: 'Dutch', id: 'nl' },
        { label: 'Polish', id: 'pl' },
        { label: 'Swedish', id: 'sv' },
        { label: 'Thai', id: 'th' },
        { label: 'Vietnamese', id: 'vi' },
        { label: 'Indonesian', id: 'id' },
        { label: 'Ukrainian', id: 'uk' },
        { label: 'Czech', id: 'cs' },
        { label: 'Greek', id: 'el' },
        { label: 'Hebrew', id: 'he' },
        { label: 'Romanian', id: 'ro' },
        { label: 'Hungarian', id: 'hu' },
        { label: 'Danish', id: 'da' },
        { label: 'Finnish', id: 'fi' },
        { label: 'Norwegian', id: 'no' },
        { label: 'Bengali', id: 'bn' },
        { label: 'Malay', id: 'ms' },
        { label: 'Filipino', id: 'tl' },
        { label: 'Swahili', id: 'sw' },
        { label: 'Urdu', id: 'ur' },
      ],
      value: () => 'es',
      required: { field: 'operation', value: 'text' },
    },
    {
      id: 'source',
      title: 'Source Language',
      type: 'dropdown',
      condition: { field: 'operation', value: 'text' },
      options: [
        { label: 'Auto-detect', id: '' },
        { label: 'English', id: 'en' },
        { label: 'Spanish', id: 'es' },
        { label: 'French', id: 'fr' },
        { label: 'German', id: 'de' },
        { label: 'Italian', id: 'it' },
        { label: 'Portuguese', id: 'pt' },
        { label: 'Russian', id: 'ru' },
        { label: 'Japanese', id: 'ja' },
        { label: 'Korean', id: 'ko' },
        { label: 'Chinese (Simplified)', id: 'zh-CN' },
        { label: 'Chinese (Traditional)', id: 'zh-TW' },
        { label: 'Arabic', id: 'ar' },
        { label: 'Hindi', id: 'hi' },
        { label: 'Turkish', id: 'tr' },
        { label: 'Dutch', id: 'nl' },
        { label: 'Polish', id: 'pl' },
      ],
      value: () => '',
    },
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      placeholder: 'Enter your Google Cloud API key',
      password: true,
      required: true,
    },
  ],
  tools: {
    access: ['google_translate_text', 'google_translate_detect'],
    config: {
      tool: (params) => `google_translate_${params.operation}`,
    },
  },
  inputs: {
    text: { type: 'string', description: 'Text to translate or detect language of' },
    target: { type: 'string', description: 'Target language code' },
    source: { type: 'string', description: 'Source language code (optional, auto-detected)' },
    apiKey: { type: 'string', description: 'Google Cloud API key' },
  },
  outputs: {
    translatedText: { type: 'string', description: 'Translated text' },
    detectedSourceLanguage: { type: 'string', description: 'Detected source language code' },
    language: { type: 'string', description: 'Detected language code' },
    confidence: { type: 'number', description: 'Detection confidence score' },
  },
}
