import { JinaAIIcon } from '@/components/icons'
import { AuthMode, type BlockConfig } from '@/blocks/types'
import type { ReadUrlResponse, SearchResponse } from '@/tools/jina/types'

export const JinaBlock: BlockConfig<ReadUrlResponse | SearchResponse> = {
  type: 'jina',
  name: 'Jina',
  description: 'Search the web or extract content from URLs',
  authMode: AuthMode.ApiKey,
  longDescription:
    'Integrate Jina AI into the workflow. Search the web and get LLM-friendly results, or extract clean content from specific URLs with advanced parsing options.',
  docsLink: 'https://docs.sim.ai/tools/jina',
  category: 'tools',
  bgColor: '#333333',
  icon: JinaAIIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Read URL', id: 'jina_read_url' },
        { label: 'Search', id: 'jina_search' },
      ],
      value: () => 'jina_read_url',
    },
    // Read URL params
    {
      id: 'url',
      title: 'URL',
      type: 'short-input',
      layout: 'full',
      required: true,
      placeholder: 'https://example.com',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'targetSelector',
      title: 'Target Selector',
      type: 'short-input',
      layout: 'full',
      placeholder: '#main-content (CSS selector)',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'waitForSelector',
      title: 'Wait For Selector',
      type: 'short-input',
      layout: 'full',
      placeholder: '.dynamic-content (CSS selector)',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'removeSelector',
      title: 'Remove Selector',
      type: 'short-input',
      layout: 'full',
      placeholder: 'header, footer, .ad (CSS selector)',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'timeout',
      title: 'Timeout (seconds)',
      type: 'short-input',
      layout: 'full',
      placeholder: '30',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'returnFormat',
      title: 'Return Format',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Markdown', id: 'markdown' },
        { label: 'HTML', id: 'html' },
        { label: 'Text', id: 'text' },
        { label: 'Screenshot', id: 'screenshot' },
        { label: 'Pageshot', id: 'pageshot' },
      ],
      value: () => 'markdown',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'retainImages',
      title: 'Retain Images',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'All', id: 'all' },
        { label: 'None', id: 'none' },
      ],
      value: () => 'all',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'engine',
      title: 'Engine',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Browser', id: 'browser' },
        { label: 'Direct', id: 'direct' },
        { label: 'CF Browser Rendering', id: 'cf-browser-rendering' },
      ],
      value: () => 'browser',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'proxy',
      title: 'Proxy (Country Code)',
      type: 'short-input',
      layout: 'full',
      placeholder: 'US, UK, auto, none',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'proxyUrl',
      title: 'Proxy URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'http://proxy.example.com:8080',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'setCookie',
      title: 'Cookies',
      type: 'short-input',
      layout: 'full',
      placeholder: 'session=abc123; token=xyz',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'tokenBudget',
      title: 'Token Budget',
      type: 'short-input',
      layout: 'full',
      placeholder: '10000',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'cacheTolerance',
      title: 'Cache Tolerance (seconds)',
      type: 'short-input',
      layout: 'full',
      placeholder: '3600',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'locale',
      title: 'Locale',
      type: 'short-input',
      layout: 'full',
      placeholder: 'en-US',
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'baseUrl',
      title: 'Base URL',
      type: 'dropdown',
      layout: 'full',
      options: [{ label: 'Final (Follow Redirects)', id: 'final' }],
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    {
      id: 'readUrlOptions',
      title: 'Options',
      type: 'checkbox-list',
      layout: 'full',
      options: [
        { label: 'Use Reader LM v2 (3x cost)', id: 'useReaderLMv2' },
        { label: 'Gather Links', id: 'gatherLinks' },
        { label: 'Gather Images', id: 'withImagesummary' },
        { label: 'Generate Image Alt Text', id: 'withGeneratedAlt' },
        { label: 'Include Iframes', id: 'withIframe' },
        { label: 'Include Shadow DOM', id: 'withShadowDom' },
        { label: 'JSON Response', id: 'jsonResponse' },
        { label: 'No Cache', id: 'noCache' },
        { label: 'Do Not Track', id: 'dnt' },
        { label: 'Disable GitHub Flavored Markdown', id: 'noGfm' },
      ],
      condition: { field: 'operation', value: 'jina_read_url' },
    },
    // Search params
    {
      id: 'q',
      title: 'Search Query',
      type: 'long-input',
      layout: 'full',
      required: true,
      placeholder: 'Enter your search query...',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'gl',
      title: 'Country Code',
      type: 'short-input',
      layout: 'full',
      placeholder: 'US, UK, JP, etc.',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'location',
      title: 'Location',
      type: 'short-input',
      layout: 'full',
      placeholder: 'New York, London, Tokyo',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'hl',
      title: 'Language Code',
      type: 'short-input',
      layout: 'full',
      placeholder: 'en, es, fr, etc.',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'num',
      title: 'Number of Results',
      type: 'short-input',
      layout: 'full',
      placeholder: '5',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'page',
      title: 'Page Number',
      type: 'short-input',
      layout: 'full',
      placeholder: '1',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'site',
      title: 'Site Restriction',
      type: 'short-input',
      layout: 'full',
      placeholder: 'jina.ai,github.com (comma-separated)',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchReturnFormat',
      title: 'Return Format',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Markdown', id: 'markdown' },
        { label: 'HTML', id: 'html' },
        { label: 'Text', id: 'text' },
      ],
      value: () => 'markdown',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchRetainImages',
      title: 'Retain Images',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'All', id: 'all' },
        { label: 'None', id: 'none' },
      ],
      value: () => 'all',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchEngine',
      title: 'Engine',
      type: 'dropdown',
      layout: 'full',
      options: [
        { label: 'Browser', id: 'browser' },
        { label: 'Direct', id: 'direct' },
      ],
      value: () => 'browser',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchTimeout',
      title: 'Timeout (seconds)',
      type: 'short-input',
      layout: 'full',
      placeholder: '30',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchSetCookie',
      title: 'Cookies',
      type: 'short-input',
      layout: 'full',
      placeholder: 'session=abc123; token=xyz',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchProxyUrl',
      title: 'Proxy URL',
      type: 'short-input',
      layout: 'full',
      placeholder: 'http://proxy.example.com:8080',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchLocale',
      title: 'Locale',
      type: 'short-input',
      layout: 'full',
      placeholder: 'en-US',
      condition: { field: 'operation', value: 'jina_search' },
    },
    {
      id: 'searchOptions',
      title: 'Options',
      type: 'checkbox-list',
      layout: 'full',
      options: [
        { label: 'Include Favicons', id: 'withFavicon' },
        { label: 'Gather Images', id: 'withImagesummary' },
        { label: 'Gather Links', id: 'withLinksummary' },
        { label: 'Generate Image Alt Text', id: 'withGeneratedAlt' },
        { label: 'No Cache', id: 'noCache' },
        { label: 'No Content (metadata only)', id: 'respondWith' },
      ],
      condition: { field: 'operation', value: 'jina_search' },
    },
    // API Key (shared)
    {
      id: 'apiKey',
      title: 'API Key',
      type: 'short-input',
      layout: 'full',
      required: true,
      placeholder: 'Enter your Jina API key',
      password: true,
    },
  ],
  tools: {
    access: ['jina_read_url', 'jina_search'],
    config: {
      tool: (params) => {
        return params.operation || 'jina_read_url'
      },
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    apiKey: { type: 'string', description: 'Jina API key' },
    // Read URL inputs
    url: { type: 'string', description: 'URL to extract' },
    useReaderLMv2: { type: 'boolean', description: 'Use Reader LM v2 (3x cost)' },
    gatherLinks: { type: 'boolean', description: 'Gather page links' },
    jsonResponse: { type: 'boolean', description: 'JSON response format' },
    targetSelector: { type: 'string', description: 'CSS selector to target' },
    waitForSelector: { type: 'string', description: 'CSS selector to wait for' },
    removeSelector: { type: 'string', description: 'CSS selector to remove' },
    timeout: { type: 'number', description: 'Timeout in seconds' },
    withImagesummary: { type: 'boolean', description: 'Gather images' },
    retainImages: { type: 'string', description: 'Retain images setting' },
    returnFormat: { type: 'string', description: 'Output format' },
    withIframe: { type: 'boolean', description: 'Include iframes' },
    withShadowDom: { type: 'boolean', description: 'Include Shadow DOM' },
    setCookie: { type: 'string', description: 'Authentication cookies' },
    proxyUrl: { type: 'string', description: 'Proxy URL' },
    proxy: { type: 'string', description: 'Proxy country code' },
    engine: { type: 'string', description: 'Rendering engine' },
    tokenBudget: { type: 'number', description: 'Token budget' },
    noCache: { type: 'boolean', description: 'Bypass cache' },
    cacheTolerance: { type: 'number', description: 'Cache tolerance seconds' },
    withGeneratedAlt: { type: 'boolean', description: 'Generate image alt text' },
    baseUrl: { type: 'string', description: 'Follow redirects' },
    locale: { type: 'string', description: 'Browser locale' },
    robotsTxt: { type: 'string', description: 'Bot User-Agent' },
    dnt: { type: 'boolean', description: 'Do Not Track' },
    noGfm: { type: 'boolean', description: 'Disable GitHub Flavored Markdown' },
    // Search inputs
    q: { type: 'string', description: 'Search query' },
    gl: { type: 'string', description: 'Country code' },
    location: { type: 'string', description: 'City location' },
    hl: { type: 'string', description: 'Language code' },
    num: { type: 'number', description: 'Number of results' },
    page: { type: 'number', description: 'Page number' },
    site: { type: 'string', description: 'Site restriction' },
    withFavicon: { type: 'boolean', description: 'Include favicons' },
    withLinksummary: { type: 'boolean', description: 'Gather links' },
    respondWith: { type: 'string', description: 'Response mode' },
    searchReturnFormat: { type: 'string', description: 'Search output format' },
    searchRetainImages: { type: 'string', description: 'Search retain images' },
    searchEngine: { type: 'string', description: 'Search engine' },
    searchTimeout: { type: 'number', description: 'Search timeout' },
    searchSetCookie: { type: 'string', description: 'Search cookies' },
    searchProxyUrl: { type: 'string', description: 'Search proxy URL' },
    searchLocale: { type: 'string', description: 'Search locale' },
  },
  outputs: {
    // Read URL outputs
    content: { type: 'string', description: 'Extracted content' },
    links: { type: 'array', description: 'List of links from page' },
    images: { type: 'array', description: 'List of images from page' },
    // Search outputs
    results: {
      type: 'array',
      description: 'Array of search results with title, description, url, and content',
    },
  },
}
